apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-postgres-dashboard.yaml
  - grafana-sa-token-secret.yaml
  
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"