
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak # Replace with the namespace ofyour Keycloak instance
spec:
  secretName: keycloak-tls # This secret will store the TLS certificate
  
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: global-issuer
  
  dnsNames:
    - keycloak-service
    - keycloak-service.keycloak.svc
    - keycloak-service.keycloak.svc.cluster.local
    - keycloak.apps.cluster.example.io # Replace with your actual domain name
  usages:
    - server auth