apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: keycloak # You can create this in the 'keycloak' namespace.
                      # The OpenShift monitoring stack usually discovers ServiceMonitors
                      # in other namespaces if properly configured (often  by default).
                      # Alternatively, create it in 'openshift-user-workload-monitoring'
                      # or your specific Prometheus namespace if  'keycloak' doesn't work.
  labels:
      # You can add a label if your Prometheus specifically looks for it, e.g.: k8s-app: keycloak-metrics
spec:
  selector:
    matchLabels:
      app: keycloak # From the service labels
      app.kubernetes.io/instance: keycloak-platform-instance # From the service labels
      app.kubernetes.io/managed-by: keycloak-operator # From the service labels
  namespaceSelector:
    matchNames:
      - keycloak
  endpoints:
  - port: https # The service port is 'https' (targets port 8443)
    path: /metrics # The path to the metrics endpoint
    scheme: https # The service port is 'https'
    tlsConfig:
      ca:
        secret:
          key: tls.crt
          name: keycloak-tls-secret
      serverName: keycloak-platform-instance-service.keycloak.svc.cluster.local # Internal service name for Keycloak       
    interval: 30s