apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  namespace: keycloak
spec:
  selector:
    app: mariadb
    role: slave
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
