apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-slave-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: gp2  # Uncomment and specify if needed
