apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-tls.yaml
  - postgres-secret.yaml
  - postgres-config.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - service-monitor.yaml
  - postgres-alerts.yaml