apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-alerts
spec:
  groups:
    - name: postgres-rules
      rules:
        - alert: PostgresDown
          expr: up{job="postgresql"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "PostgreSQL instance is down ({{ $labels.instance }})"
            description: "PostgreSQL exporter for {{ $labels.instance }} is not reachable for 1 minute."
        - alert: PostgresTooManyConnections
          expr: sum(pg_stat_activity_count) by (instance) /sum(pg_settings_max_connections) by (instance) > 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High PostgreSQL connection usage on {{ $labels.instance }}"
            description: | 
              Connection usage is above 90% ({{ $value | humanizePercentage }}).
        - alert: PostgresSlowQueries
          expr: rate(pg_stat_activity_max_tx_duration{state="active"}[5m]) > 30
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Long running PostgreSQL transactions ({{ $labels.instance }})"
            description: "Detected transactions running longer than 30s in last 5 minutes."
        - alert: PostgresDiskSpaceLow
          expr: kubelet_volume_stats_used_bytes{namespace="keycloak", persistentvolumeclaim="postgresql-pvc"} / kubelet_volume_stats_capacity_bytes{namespace="keycloak", persistentvolumeclaim="postgresql-pvc"} > 0.8
          labels:
            severity: critical
          annotations:
            summary: "Low disk space for PostgreSQL Storage PVC ({{ $labels.instance }})"
            description: "Available disk space is below 20%."
        # Alert on high cache hit ratio drop
        - alert: PostgresLowCacheHitRatio
          expr: (pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read)) < 0.9
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Low PostgreSQL cache hit ratio ({{ $labels.instance }})"
            description: "Cache hit ratio is below 90%. Consider tuning shared_buffers or queries."
        # Alert on too many deadlocks
        - alert: PostgresDeadlocks
          expr: increase(pg_stat_database_deadlocks[5m]) > 5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High number of deadlocks in PostgreSQL ({{ $labels.instance }})"
            description: "More than 5 deadlocks detected in the last 5 minutes."
        # Alert on high WAL files generation
        - alert: PostgresHighWalActivity
          expr: rate(pg_stat_archiver_archived_count[5m]) > 50
          for: 5m
          labels:
            severity: info
          annotations:
            summary: "High WAL archival activity ({{ $labels.instance }})"
            description: "PostgreSQL WAL files archived at a high rate."
        - alert: PostgresPodHighCpuLimitUsage
          expr: |
            sum(rate(container_cpu_usage_seconds_total{container="postgres", namespace="keycloak"}[5m])) by (pod)
            /
            sum(container_spec_cpu_quota{container="postgres", namespace="keycloak"} / container_spec_cpu_period{container="keycloak", namespace="keycloak"}) by (pod)
            > 0.9
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Postgres pod {{ $labels.pod }} is using over 90% of its CPU limit"
            description: |
              Pod {{ $labels.pod }} is using more than 90% of its allocated CPU limit over the last 5 minutes.
              Consider increasing limits or investigating performance issues.
        - alert: PostgresHighMemory
          expr: (container_memory_usage_bytes{container="postgres", namespace="keycloak"} / container_spec_memory_limit_bytes{container="postgres", namespace="keycloak"}) > 0.9
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Postgres memory usage is high"
            description: |
              Memory usage is above 90% of the container's memory limit.

