apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      volumes:
      - name: datasource-volume
        emptyDir: {}
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter
        env:
          - name: DATA_SOURCE_URI
            value: postgresql.keycloak.svc.cluster.local:5432/keycloak?sslmode=require
          - name: DATA_SOURCE_USER
            value: postgres
          - name: DATA_SOURCE_PASS 
            valueFrom:
              secretKeyRef:
                key: postgres-admin-password
                name: postgresql-secret
        ports:
        - containerPort: 9187
        volumeMounts:
        - name: datasource-volume
          mountPath: /etc/exporter
        command:
        - /bin/sh
        - -c
        - |
          exec /bin/postgres_exporter --web.listen-address=:9187
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9187
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi