apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: postgres-exporter   # Match the label on the Service that exposes the exporter
  namespaceSelector:
    matchNames:
      - keycloak            # Namespace where the exporter Service exists
  endpoints:
    - port: metrics            # Name of the port exposed in the Service (see below)
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s