# RBAC permissions for the job
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bearer-token-creator
  namespace: keycloak  # Changed from monitoring to keycloak
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-manager
  namespace: keycloak  
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-manager
  namespace: keycloak  
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bearer-token-creator
  namespace: keycloak  
subjects:
- kind: ServiceAccount
  name: default
  namespace: keycloak
roleRef:
  kind: Role
  name: bearer-token-creator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-manager
  namespace: keycloak  
subjects:
- kind: ServiceAccount
  name: default
  namespace: keycloak
roleRef:
  kind: Role
  name: pvc-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-manager
  namespace: keycloak  
subjects:
- kind: ServiceAccount
  name: default
  namespace: keycloak
roleRef:
  kind: ClusterRole
  name: pv-manager
  apiGroup: rbac.authorization.k8s.io