apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-class.yaml
  - postgres-tls.yaml
  - postgres-secret.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"