apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-class.yaml
  - default-sa-role.yaml
  - prometheus-role.yaml
  - postgres-tls.yaml
  - postgres-secret.yaml
  - grafana.yaml
  - grafana-dashboard-config.yaml
  - grafana-ds-config.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"