apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-csi-immediate
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: Immediate
reclaimPolicy: Retain
