apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay
  namespace: quay-registry
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    repoURL: https://github.com/ocp-keycloak-solution/gitops-manifest.git
    targetRevision: main
    path: manifest/quay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true