apiVersion: v1
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: quay-registry
type: Opaque
stringData:
  config.yaml: |
    # ... your other existing settings (LOGGING, SUPER_USERS, etc.)
    
    AUTHENTICATION_TYPE: OIDC
    FEATURE_USER_INITIALIZE: true
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: true 
    FEATURE_TEAM_SYNCING: true
    FEATURE_UI_V2: true

    OIDC_LOGIN_CONFIG:
      OIDC_SERVER: "https://keycloak.apps.cluster-8pq26.dynamic.redhatworkshops.io/realms/openshift/"
      CLIENT_ID: "quay-client"
      CLIENT_SECRET: "QUAY_CLIENT_SECRET_PLACEHOLDER"
      SERVICE_NAME: "Keycloak"
      DEBUGLOG: true
      LOGIN_SCOPES:
        - "openid"
       
      PREFERRED_USERNAME_CLAIM_NAME: "preferred_username"
      PREFERRED_GROUP_CLAIM_NAME: "groups"
      VERIFIED_EMAIL_CLAIM_NAME: "email"
    
    SUPER_USERS:
      - "openshift-admin" # user added in  KeycloakRealmImport
      - "keycloak-admin" # user added in  KeycloakRealmImport
