apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins
  annotations:
    # This annotation is often present on system-managed resources.
    # OpenShift might try to reconcile changes to this binding if it's
    # strictly managed by an operator, but modifying 'cluster-admins'
    # to add administrative groups is a common practice.
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:cluster-admins # Keeps the default system group
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin # Keeps the default system admin user
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: cluster-admins   # Adds your group-sync managed group