
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-group-sync
  namespace: group-sync-operator
type: Opaque
stringData:
  username: "group-sync-svc"
  password: "changeme" # This should be replaced with actual 