apiVersion: batch/v1
kind: CronJob
metadata:
  name: keycloak-import-realm
spec:
  schedule: "0 0 31 2 *"  # This date never exists, so the job will never trigger, only trigger manually
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: keycloak-export
            image: registry.redhat.io/rhbk/keycloak-rhel9@sha256:16fb22cfaf27bf9eb7a11e873dc251bef8ff77e2e6a09c70c2c8a3cefa3d0aa5
            env:
              - name: REALM_FILE
                value: master-realm.json
              - name: BACKUP_DIR
                value: /keycloak-backup/export-master-latest # directory contains the import files, the default dir that cron_export use is export_master_latest
              - name: KC_DB
                value: postgres
              - name: KC_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: database-user
              - name: KC_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: database-password
              - name: KC_DB_URL
                value: 'jdbc:postgresql://postgresql:5432/keycloak?sslmode=require'
              - name: KC_CACHE
                value: "local"            
            command: ["/bin/sh", "-c"]
            args:
              - |
          
                source /kc-config/patch-realm.sh /kc-config/mappings.txt $BACKUP_DIR/$REALM_FILE

                echo "import from $BACKUP_DIR"

                /opt/keycloak/bin/kc.sh import \
                  --dir=$BACKUP_DIR

            volumeMounts:
              - name: backup-volume
                mountPath: /keycloak-backup
              - name: config
                mountPath: /kc-config
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: keycloak-backup-pvc
            - name: config
              configMap:
                name: kc-import-config