apiVersion: k8s.keycloak.org/v2alpha1 
kind: Keycloak
metadata:
  name: keycloak-platform-instance # Renamed for clarity
  labels:
    app: keycloak-platform # Label for KeycloakRealm's instanceSelector
spec:
  instances: 1 
  db:
    vendor: postgres
    url: "jdbc:postgresql://postgresql:5432/keycloak?sslmode=require"
    usernameSecret:
      name:  postgresql-secret
      key: database-user # Must match secretKey in postgres/postgres-secret.yaml
    passwordSecret:
      name: postgresql-secret
      key: database-password # Must match secretKey in postgres/postgres-secret.yaml
   
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: keycloak.apps.cluster.example.io # THIS MUST BE PATCHED BY OVERLAYS
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: metrics-enabled
      value: 'true'
    - name: http-metrics-histograms-enabled
      value: 'true'
    - name: cache-metrics-histograms-enabled
      value: 'true'
    - name: http-metrics-slos
      value: '5,10,25,50,250,500,1000,2500,5000,10000'
    - name: event-metrics-user-enabled
      value: 'true'
    - name: event-metrics-user-tags
      value: 'realm,idp,clientId'
    - name: spi-events-listener-jboss-logging-success-level
      value: info
    - name: log-console-output
      value: json
    - name: http-max-queued-requests
      value: '1000'
    - name: http-pool-max-threads
      value: '50'
    - name: log-level
      value: INFO
  
  

  
 
