apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: openshift-realm-import
spec:
  keycloakCRName: keycloak-platform-instance
  realm:
    id: openshift
    realm: openshift
    displayName: "OpenShift Authentication"
    enabled: true
    sslRequired: "external"
    accessTokenLifespan: 300
    ssoSessionIdleTimeout: 1800
    ssoSessionMaxLifespan: 36000
    accessCodeLifespan: 60
    accessCodeLifespanUserAction: 300

    # Users section with admin user
    users:

      - username: "keycloak-admin"
        enabled: true
        email: "admin@example.com"
        firstName: "Keycloak"
        lastName: "Administrator"
        emailVerified: true
        credentials:
          - type: "password"
            value: "changeme"  # Change this to a secure password
            temporary: false
        realmRoles:
          - "admin"
          - "cluster-admin"
        groups:
          - "cluster-admins"
          - "developers"
          - "ssoadmin"
          - "admin"
      
      - username: "openshift-admin"
        enabled: true
        email: "openshift-admin@example.com"
        firstName: "OpenShift"
        lastName: "Administrator"
        emailVerified: true
        credentials:
          - type: "password"
            value: "changeme"  # Change this to a secure password
            temporary: false
        realmRoles:
          - "admin"
          - "cluster-admin"
        groups:
          - "cluster-admins"
          - "developers"
          - "ssoadmin"
          - "admin"
      # Group Sync Service Account
      - username: "group-sync-svc"
        enabled: true
        email: "group-sync-svc@example.com"
        firstName: "GroupSync"
        lastName: "Operator"
        emailVerified: true
        clientRoles:
          openshift-client:
            - "query-groups"
            - "query-users"
            - "view-users"
        credentials:
          - type: "password"
            value: "changeme"  # Change this to a secure password
            temporary: false
    
    
    # Groups
    groups:
      - name: cluster-admins
        path: /cluster-admins
        attributes:
          openshift-role: ["cluster-admin"]
      - name: developers
        path: /developers
        attributes:
          openshift-role: ["basic-user"]
      - name: ssoadmin
        path: /ssoadmin
        attributes: 
          openshift-role: ["ssoadmin"]
      - name: admin
        path: /admin
        attributes: 
          openshift-role: ["admin"]
    
    # Roles
    roles:
      realm:
        - name: openshift-admin
          description: "OpenShift Cluster Administrator"
        - name: openshift-developer
          description: "OpenShift Developer"

    clientScopes:
      - name: openid
        protocol: openid-connect
      - name: profile
        protocol: openid-connect
      - name: email
        protocol: openid-connect
      - name: groups
        protocol: openid-connect
        protocolMappers:
          - name: "groups"
            protocol: "openid-connect"
            protocolMapper: "oidc-group-membership-mapper"
            config:
              "access.token.claim": "true"
              "claim.name": "groups"
              "id.token.claim": "true"
              "userinfo.token.claim": "true"
              "full.path": "false"
    # Clients
    clients:
      # OpenShift OAuth Client
      - clientId: openshift-client
        name: "OpenShift Console"
        description: "OpenShift Console OAuth Client"
        enabled: true
        protocol: openid-connect
        defaultClientScopes:
          - "openid"
          - "profile"
          - "email"
          - "groups"
       
        consentRequired: false
        clientAuthentication: true
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        implicitFlowEnabled: false
        standardFlowEnabled: true
        secret: OGFtFrsPnmzCAtV8wCWxqUFisZ6P39gT
        redirectUris:
          - "https://oauth-openshift.apps.changeme/oauth2callback/keycloak"
        webOrigins:
          - "https://console-openshift-console.apps.changeme"
          - "https://oauth-openshift.apps.changeme"
        protocolMappers:
          - name: "preferred_username"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-property-mapper"
            config:
              "access.token.claim": "true"
              "claim.name": "preferred_username"
              "id.token.claim": "true"
              "user.attribute": "username"
              "userinfo.token.claim": "true"
      
           # QUAY 
      - clientId: quay-client
        name: "Quay Registry"
        description: "Quay Registry OAuth Client"
        enabled: true
        protocol: openid-connect
        defaultClientScopes:
          - "openid"
          - "profile"
          - "email"
          - "groups"
       
        consentRequired: false
        clientAuthentication: true
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        implicitFlowEnabled: false
        standardFlowEnabled: true
        secret: QUAY_CLIENT_SECRET_PLACEHOLDER  # Replace with actual secret
        redirectUris:
          - "https://example-quay-quay-registry.apps.cluster-8pq26.dynamic.redhatworkshops.io/oauth2/oidc/callback"
        webOrigins:
          - "https://example-quay-quay-registry.apps.cluster-8pq26.dynamic.redhatworkshops.io"
        protocolMappers:
          - name: "preferred_username"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-property-mapper"
            config:
              "access.token.claim": "true"
              "claim.name": "preferred_username"
              "id.token.claim": "true"
              "user.attribute": "username"
              "userinfo.token.claim": "true"
      
     

