apiVersion: k8s.keycloak.org/v2alpha1 
kind: Keycloak
metadata:
  name: keycloak-platform-instance # Renamed for clarity
  namespace: keycloak
  labels:
    app: keycloak-platform # Label for KeycloakRealm's instanceSelector
spec:
  instances: 1 
  db:
    vendor: postgres
    host: postgresql # Service name of PostgreSQL
    database: keycloak #
    port: 5432 # Default PostgreSQL port, can be omitted if using default
    usernameSecret:
      name:  postgresql-secret
      key: database-user # Must match secretKey in postgres/postgres-secret.yaml
    passwordSecret:
      name: postgresql-secret
      key: database-password # Must match secretKey in postgres/postgres-secret.yaml
   
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: keycloak.apps.cluster.example.io # THIS MUST BE PATCHED BY OVERLAYS
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: metrics-enabled
      value: 'true'

  
 
