apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml # Keycloak CR
  - certificate.yaml # TLS certificate
  - service-monitor.yaml # ServiceMonitor for Prometheus
  - keycloak-backup-pvc.yaml
  - cron-export-realm.yaml
  - cron-import-realm.yaml
