apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
spec:
  selector:
    matchLabels:
      app: keycloak
 
  endpoints:
  - port: management 
    path: /metrics # The path to the metrics endpoint
    scheme: https # The service port is 'https'
    tlsConfig:
      serverName: keycloak-platform-instance-service.keycloak.svc.cluster.local 
      insecureSkipVerify: true # Set to true if you are using self-signed certificates
    interval: 30s # Scrape interval, adjust as needed
  