apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak 

spec:
  issuerRef:
    name: zerossl-production-ec2
  dnsNames:
    - keycloak.apps.cluster-8pq26.dynamic.redhatworkshops.io
