apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-platform-instance # Must match the name in the base
  namespace: keycloak # Must match the namespace in the base
spec:
  hostname:
    hostname: keycloak.apps.cluster-8pq26.dynamic.redhatworkshops.io