apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: openshift-realm-import
  namespace: keycloak
spec:
  realm:
    clients:
      # OpenShift OAuth Client
      - clientId: openshift-client
        redirectUris:
          - "https://oauth-openshift.apps.cluster-8pq26.dynamic.redhatworkshops.io/oauth2callback/keycloak"
        webOrigins:
          - "https://console-openshift-console.apps.cluster-8pq26.dynamic.redhatworkshops.io"
          - "https://oauth-openshift.apps.cluster-8pq26.dynamic.redhatworkshops.io"
      
      # ArgoCD OAuth Client
      - clientId: argocd-client
        redirectUris:
          - "https://openshift-gitops-server-openshift-gitops.apps.cluster-8pq26.dynamic.redhatworkshops.io/auth/callback"
        webOrigins:
          - "https://openshift-gitops-server-openshift-gitops.apps.cluster-8pq26.dynamic.redhatworkshops.io"
