apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-metrics
  namespace: keycloak 

spec:
  endpoints:
  - port: https
    tlsConfig:
      serverName: keycloak.apps.cluster-8pq26.dynamic.redhatworkshops.io