apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-download
spec:
  schedule: "0 2 * * *"  # daily at 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: download-minio
            image: minio/mc:latest
            command:
              - sh
              - -c
              - |
                export HOME=/tmp
                mc alias set myminio $MINIO_URL $MINIO_USER $MINIO_PASSWORD && \
                MINIO_SRC_DIR=myminio/$MINIO_BUCKET/$IMPORT_DIR
                TGT=/keycloak-backup/minio
            
                mkdir -p $TGT

                echo "download $MINIO_SRC_DIR to $TGT"

                mc cp --recursive $MINIO_SRC_DIR $TGT
                
                ls $TGT
            env:
              - name: MINIO_URL
                value: "https://minio-api-keycloak.apps.cluster-pngcm.pngcm.sandbox2375.opentlc.com"
              - name: MINIO_USER
                valueFrom:
                  secretKeyRef:
                    name: minio-secret
                    key: root-user
              - name: MINIO_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: minio-secret
                    key: root-password
              - name: MINIO_BUCKET
                value: keycloak-realm-backup
              - name: IMPORT_DIR
                value: export-master-latest
            volumeMounts:
              - name: backup-volume
                mountPath: /keycloak-backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: keycloak-backup-pvc