apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-monitoring
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/ocp-keycloak-solution/gitops-manifest.git
    targetRevision: main
    path: manifest/cert-issuer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true