apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak/application-dev.yaml
  - postgres/application.yaml
  - grafana/application.yaml
  - openshift-monitoring/application.yaml
  - cert-issuer/application.yaml
  - minio/application.yaml