apiVersion: batch/v1
kind: CronJob
metadata:
  name: keycloak-export-realm
spec:
  schedule: "0 2 * * *"  # daily at 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: keycloak-export
            image: registry.redhat.io/rhbk/keycloak-rhel9@sha256:16fb22cfaf27bf9eb7a11e873dc251bef8ff77e2e6a09c70c2c8a3cefa3d0aa5
            env:
              - name: REALM
                value: openshift 
              - name: KC_DB
                value: postgres
              - name: KC_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: database-user
              - name: KC_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql-secret
                    key: database-password
              - name: KC_DB_URL
                value: 'jdbc:postgresql://postgresql:5432/keycloak?sslmode=require'
              - name: KC_CACHE
                value: "local"            
            command: ["/bin/sh", "-c"]
            args:
              - |
                TIMESTAMP=$(date +%Y%m%d%H%M%S)
                EXPORT_DIR=/keycloak-backup/export-$REALM-$$TIMESTAMP
                EXPORT_DIR_LATEST=/keycloak-backup/export-$REALM-latest

                # remove backup files older than 7 days
                find /keycloak-backup -type d -name 'export-*' -mtime +7 -exec rm -rf {} +

                /opt/keycloak/bin/kc.sh export \
                  --realm=$REALM \
                  --dir=$EXPORT_DIR \
                  --users=realm_file
                
                if [ -d $EXPORT_DIR_LATEST ]; then
                  rm -rf $EXPORT_DIR_LATEST
                fi
                
                # soft link to export_$REALM_latest for latest backup
                ln -sf $EXPORT_DIR $EXPORT_DIR_LATEST
                
                echo "exported files for realm $REALM"
                ls -l $EXPORT_DIR_LATEST
                ls $EXPORT_DIR_LATEST
            volumeMounts:
              - name: backup-volume
                mountPath: /keycloak-backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: keycloak-backup-pvc