{
 "title": "Keycloak capacity planning dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "realm", "label": "realm", "query": { "query": "label_values(realm)" } }
  ]
 },
 "panels": [
  {
   "title": "Password validations rate",
   "type": "timeseries",
   "description": "Shows the number of password validations performed by Keycloak",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(keycloak_credentials_password_hashing_validations_total{namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}} => {{outcome}} - {{algorithm}}:{{hashing_strength}}"
    }
   ]
  },
  {
   "title": "Code to Token Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keycloak_user_events_total{event=\"code_to_token\", namespace=\"$namespace\", realm=\"$realm\", error!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{error}}"
    },
    {
     "expr": "irate(keycloak_user_events_total{event=\"code_to_token\", namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client Login Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keycloak_user_events_total{event=\"client_login\", namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(keycloak_user_events_total{event=\"client_login\", namespace=\"$namespace\", realm=\"$realm\", error!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  },
  {
   "title": "Refresh Token Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keycloak_user_events_total{event=\"refresh_token\", namespace=\"$namespace\", realm=\"$realm\", error!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{error}}"
    },
    {
     "expr": "irate(keycloak_user_events_total{event=\"refresh_token\", namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Login Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keycloak_user_events_total{event=\"login\", namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(keycloak_user_events_total{event=\"login\", namespace=\"$namespace\", realm=\"$realm\", error!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  },
  {
   "title": "Logout Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keycloak_user_events_total{event=\"logout\", namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(keycloak_user_events_total{event=\"logout\", namespace=\"$namespace\", realm=\"$realm\", error!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  },
  {
   "title": "Token Exchange Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(keycloak_user_events_total{event=\"token_exchange\", namespace=\"$namespace\", realm=\"$realm\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(keycloak_user_events_total{event=\"token_exchange\", namespace=\"$namespace\", realm=\"$realm\", error!=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  }
 ]
}