apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
    folders: grafana
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: admin
      admin_user: root
    persistence:
      accessModes: ReadWriteOnce
      enabled: 'true'
      size: 5Gi