apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-config.yaml
  - postgres-pvc.yaml
  - postgres-backup-pvc.yaml
  
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"