apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  storageClassName: gp3-csi-immediate
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup-pvc
spec:
  storageClassName: gp3-csi-immediate
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi