apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cron-pg-backup-ls.yaml
  - cron-pg-backup.yaml
  - cron-pg-restore.yaml
  
commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"