apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - service-monitor.yaml
  
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"