apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-dashboard.yaml
  - grafana-sa-token-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"