apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-oauth
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    repoURL: https://github.com/ocp-keycloak-solution/gitops-manifest.git
    targetRevision: main
    path: manifest/openshift-oauth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: v4-0-config-user-idp-0-client-secret
      namespace: openshift-authentication
      jsonPointers:
        - /data/clientSecret
