apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-oauth-keycloak-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/keycloak-gitops-manifest.git
    targetRevision: th-openshift-oauth
    path: manifest/openshift-oauth/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
