apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealm
metadata:
  name: openshift-realm
  namespace: keycloak
spec:
  instanceSelector:
    matchLabels:
      app: keycloak-platform
  realm:
    id: openshift
    realm: openshift
    enabled: true
    displayName: "OpenShift SSO Realm"
    loginTheme: "keycloak"
    accountTheme: "keycloak"
    adminTheme: "keycloak"
    emailTheme: "keycloak"
    sslRequired: "external"
    userManagedAccessAllowed: false
    registrationAllowed: false
    registrationEmailAsUsername: false
    rememberMe: true
    verifyEmail: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true
    permanentLockout: false
    maxFailureWaitSeconds: 900
    minimumQuickLoginWaitSeconds: 60
    waitIncrementSeconds: 60
    quickLoginCheckMilliSeconds: 1000
    maxDeltaTimeSeconds: 43200
    failureFactor: 30
    roles:
      realm:
      - name: "openshift-admin"
        description: "OpenShift Cluster Admin"
      - name: "openshift-developer"
        description: "OpenShift Developer"
      - name: "argo-admin"
        description: "ArgoCD Admin"
      - name: "argo-readonly"
        description: "ArgoCD Read Only"
    groups:
    - name: "cluster-admins"
      path: "/cluster-admins"
      realmRoles:
      - "openshift-admin"
      - "argo-admin"
    - name: "developers"
      path: "/developers"
      realmRoles:
      - "openshift-developer"
      - "argo-readonly"
    users:
    - username: "admin"
      enabled: true
      email: "admin@example.com"
      firstName: "System"
      lastName: "Administrator"
      groups:
      - "/cluster-admins"
      credentials:
      - type: "password"
        value: "admin123"
        temporary: false
