apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakClient
metadata:
  name: openshift-client
  namespace: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak-platform
  client:
    clientId: openshift
    name: "OpenShift OAuth Client"
    description: "OpenShift OAuth Integration"
    enabled: true
    clientAuthenticatorType: "client-secret"
    secret: "your-openshift-client-secret"
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: true
    protocol: "openid-connect"
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultClientScopes:
    - "web-origins"
    - "role_list"
    - "profile"
    - "roles"
    - "email"
    redirectUris:
    - "https://oauth-openshift.apps.cluster.example.io/oauth2callback/keycloak"
    webOrigins:
    - "https://console-openshift-console.apps.cluster.example.io"
    - "https://oauth-openshift.apps.cluster.example.io"
    protocolMappers:
    - name: "groups"
      protocol: "openid-connect"
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "claim.name": "groups"
        "full.path": "false"
        "id.token.claim": "true"
        "access.token.claim": "true"
        "userinfo.token.claim": "true"
    - name: "preferred_username"
      protocol: "openid-connect"
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        "user.attribute": "username"
        "claim.name": "preferred_username"
        "id.token.claim": "true"
        "access.token.claim": "true"
        "userinfo.token.claim": "true"
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakClient
metadata:
  name: argocd-client
  namespace: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak-platform
  client:
    clientId: argocd
    name: "ArgoCD OAuth Client"
    description: "ArgoCD OAuth Integration"
    enabled: true
    clientAuthenticatorType: "client-secret"
    secret: "your-argocd-client-secret"
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: true
    protocol: "openid-connect"
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultClientScopes:
    - "web-origins"
    - "role_list"
    - "profile"
    - "roles"
    - "email"
    redirectUris:
    - "https://argocd-server-openshift-gitops.apps.cluster.example.io/auth/callback"
    - "https://argocd.apps.cluster.example.io/auth/callback"
    webOrigins:
    - "https://argocd-server-openshift-gitops.apps.cluster.example.io"
    - "https://argocd.apps.cluster.example.io"
    protocolMappers:
    - name: "groups"
      protocol: "openid-connect"
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "claim.name": "groups"
        "full.path": "false"
        "id.token.claim": "true"
        "access.token.claim": "true"
        "userinfo.token.claim": "true"
    - name: "preferred_username"
      protocol: "openid-connect"
      protocolMapper: "oidc-usermodel-property-mapper"
      config:
        "user.attribute": "username"
        "claim.name": "preferred_username"
        "id.token.claim": "true"
        "access.token.claim": "true"
        "userinfo.token.claim": "true"
