
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oauth-secret
  namespace: openshift-config
type: Opaque
stringData:
  clientSecret: "your-openshift-client-secret" # This should be replaced with actual secret